# Generated by Django 5.2.1 on 2025-05-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_companyprofile_invoice_invoiceline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="system.customer"
            ),
        ),
    ]
