# Generated by Django 5.2.1 on 2025-05-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_alter_invoice_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="system.product",
            ),
        ),
    ]
