# Generated by Django 5.2.1 on 2025-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_alter_invoiceline_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_term",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "10 days"),
                    (15, "15 days"),
                    (30, "30 days"),
                    (60, "60 days"),
                ],
                default=30,
            ),
        ),
    ]
