# Generated by Django 5.2.1 on 2025-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0008_invoice_payment_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
