# Generated by Django 5.2.1 on 2025-05-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid",
            field=models.BooleanField(
                default=False, help_text="Tick when full payment has been received."
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reminder_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reminders",
                to="system.invoice",
            ),
        ),
    ]
