# Generated by Django 5.2.1 on 2025-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0010_invoice_paid_invoice_reminder_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="bankgiro",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Bankgiro"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="iban",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="IBAN"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="swish",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Swish"
            ),
        ),
    ]
