# Generated by Django 5.2.1 on 2025-05-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_companyprofile_bankgiro_companyprofile_iban_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_lines",
                to="system.product",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
